import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center my-10">
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div>
            <Link href="/" className="text-2xl text-bold">
              PokemonFinder
            </Link>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
